services:
  web:
    build: .
    entrypoint: ["/usr/src/app/reset_db.sh"]  # Asegúrate de que este archivo existe y tiene permisos de ejecución
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Ajuste para SQLite
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}