services:
  web:
    build: .
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    mem_limit: 512m
    environment:
      - DATABASE_URL=sqlite3:///app/db/development.sqlite3  # Ajuste para SQLite
      - SECRET_KEY_BASE=iSgLqm+WxMEFcwAdS3v7+1Qfdpgu4KDzalY2DJGjV/0XwmJ1lta+y6gLxPA5LBOE9WxZCfaPY75MTKgDCgvWXAyF5U4PoSGIqcRoNOvd6XUrd4REV2FJrlMTfCuXQua8AcRvEhxL1DcebghxKkw/vSN4AlAHAFypbLzIzdrhyo9AHSCV3sYQH5+IuLDl3a15WoltyZ05wKTva14QGyKOpnpWw213o0/tdHbz2iXiMkLt50Nly2kQGJ5kozZeAVx1hPETArXJ3WaBCl7fke1XPimaTTpsTttNDYYUXzbsvkYB4vcJOWF+cX9PANCdJhg5e5luX00qJU1NzqOFjOeeniqlAoMITK8RgKRpNGaaxdapqDRN02gAYPSkx9Dst6yTdh4ITDr153rkzwDzqgiK8NM1RBx4--gZSXIGSNwCktlg4P--Z6eqXPX8kgGxOT/2wy9IQQ==
    depends_on:
      - db

  db:
    image: busybox
    volumes:
      - db-data:/app/db  # Volumen para la base de datos SQLite

volumes:
  db-data:
